### ISSUE TITLE
tgm integration

### ISSUE THREAD

**Issue by svenl77** [Themekraft/wc4bp-xprofile#12]
After the tgm integration in the core I run into the following issue:

( ! ) Fatal error: Uncaught Error: Call to undefined function WC() in /Users/svenl77/Sites/buddyforms/wp-content/plugins/wc4bp-checkout-manager/admin/admin-xprofile.php on line 40

Wee need to integrate tgm in the extension too

**Comment by gfirem** [comment]
I get other error from WC. But is an bug into woocommerce not release yet 

https://github.com/woocommerce/woocommerce/issues/12969

![image](https://cloud.githubusercontent.com/assets/11023116/22427672/75f6aa44-e6da-11e6-9124-b6f3fd0cb97b.png)
