### ISSUE TITLE
COMDITIONAL VISIBILITY SELECT FIELD NOT WORKING

### ISSUE THREAD

**Issue by svenl77** [Themekraft/wc4bp-xprofile#14]
Hi there, when I try to set conditional visibility in BuddyPress xProfile the select fields return no results. I am positive the products and categories are there

**Comment by svenl77** [comment]
![screenshot_051017_020551_pm](https://cloud.githubusercontent.com/assets/645567/25942662/aba84c76-363d-11e7-8168-2bf6071b4e78.jpg)

Getting an error when checking 'Make this group hidden on the checkout page, unless at least one of the following criteria are met:'



Select2 doesn't like something….

**Comment by svenl77** [comment]
For starters readonly has been deprecated in select2



\wc4bp-xprofile-master\wc4bp-xprofile-master\assets\js\admin-xprofile.js



Line 12



$checkbox.change(function () {

if ($(this).is(":checked")) {

$container.find('.wc-search').select2('readonly', false);

$container.find('.field.cv-products, .field.cv-categories').removeClass('disabled');

} else {

$container.find('.wc-search').select2('readonly', true);

$container.find('.field.cv-products, .field.cv-categories').addClass('disabled');

}

});



When I change that to



$checkbox.change(function () {

if ($(this).is(":checked")) {

$container.find('.wc-search').select2();

$container.find('.field.cv-products, .field.cv-categories').removeClass('disabled');

} else {

$container.find('.wc-search').select2();

$container.find('.field.cv-products, .field.cv-categories').addClass('disabled');

}

});



The errors go away but the input fields still return no results, I'm thinking this is probably a WooCommerce 3.0 issue. Reading that product ids are protected now.

**Comment by i2g-lweiss** [comment]
Looks like we have 4 functions that are not returning results
![screenshot_051117_104639_am](https://cloud.githubusercontent.com/assets/14227495/25963753/4a86128a-3637-11e7-905c-549624390c72.jpg)

**Comment by i2g-lweiss** [comment]
Was able to get it working using a filter

add_filter( 'wc4bp_xprofile_conditional_visibility_categories', 'filter_wc4bp_xprofile_conditional_visibility_categories', 10, 3 );
function filter_wc4bp_xprofile_conditional_visibility_categories($wc4bp_xprofile_conditional_visibility_categories,$group_id,$group){
	if ( $group_id == 4){
		$wc4bp_xprofile_conditional_visibility_categories = array(255);
	}
	return $wc4bp_xprofile_conditional_visibility_categories;
}

The Select2 input field still does not work but the fact that this does should narrow down the cause a bit.  Likely not a WooCommerce 3.0 issue unless it's specific to Select2.

**Comment by svenl77** [comment]
@gfirem what about this one?

**Comment by i2g-lweiss** [comment]
Any updates on this?  Still not working and my filter no longer works either.  Customers cannot make orders so had to disable both wc4bp plugins

**Comment by gfirem** [comment]
The issue here is cause by the way is called select2 in the plugins, it use a deprecated way. We need to change that functionality. @marin250189

**Comment by EkoJR** [comment]
I want to confirm this is working.

I was about to comment the same issue, until I noticed the development branch with the a93a59dc013910bf0b3c6dddf60b1f6fe699d6e0 commit merged into it.

Figured I would tag it, and confirm it before public release.

**Comment by gfirem** [comment]
Thanks @EkoJr, i think this fix is include in the current release. If you face some issue, please share with us.
