### ISSUE TITLE
wc4bp_wc_categories_that_allow_group_visibility

### ISSUE THREAD

**Issue by svenl77** [Themekraft/wc4bp-xprofile#15]
Tried using the filter mentioned here http://docs.themekraft.com/article/374-allow-visibility-of-xprofile-field-groups-to-depend-on-products-or-categories-in-cart but I think that's out of date cause 'wc4bp_wc_categories_that_allow_group_visibility' does not exist in the plugin. Tried this http://hookr.io/plugins/wc4bp-buddypress-xprofile-checkout-manager/1.2/filters/wc4bp_xprofile_conditional_visibility_categories/ and just got a white screen. Thanks, Lawrence PS somebody mentioned that the paid version of WC4BP is required for this xprofile checkout to work. Is this true? We purchased it in the past but I can't get access to it.

**Comment by i2g-lweiss** [comment]
This is still an issue, any progress?

**Comment by gfirem** [comment]
The filter existing in the code related to conditional visibility. They are:
* **wc4bp_xprofile_conditional_visibility_enabled**. Enabled or disable this option.
* **wc4bp_xprofile_conditional_visibility_products**. Filter the conditional visibility for Products.
* **wc4bp_xprofile_conditional_visibility_categories**. Filter the conditional visibility for Categories.
