### ISSUE TITLE
WC4BP Checkout Manager Issue - BP Profile sync is set to OFF

### ISSUE THREAD

**Issue by svenl77** [Themekraft/wc4bp-xprofile#3]
BP Profile sync is set to OFF. when a user registers via http://site.com/register/ then the next page of check your eamil for activation doesnt come up. get the following debug logs

Warning: Invalid argument supplied for foreach() in /site.com/wp-content/plugins/woocommerce-buddypress-integration-xprofile-checkout-manager/includes/wc4bp-xprofile-checkout.php on line 243

Warning: Invalid argument supplied for foreach() in /site.com/wp-content/plugins/woocommerce-buddypress-integration-xprofile-checkout-manager/includes/wc4bp-xprofile-checkout.php on line 246

Fatal error: Call to undefined function wc4bp_sync_addresses_from_profile() in /site.com/wp-content/plugins/woocommerce-buddypress-integration-xprofile-checkout-manager/includes/wc4bp-xprofile-checkout.php on line 251

**Comment by svenl77** [comment]
Is this one fixed?

**Comment by kish2011** [comment]
No, sorry I have missed it. I start on it soon

**Comment by kish2011** [comment]
I did a pull request
